//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ADMS
{
    using System;
    using System.Collections.Generic;
    
    public partial class JOB_CIRCULARS
    {
        public short C_ID { get; set; }
        public string C_TITLE { get; set; }
        public string J_POSITION { get; set; }
        public string JOB_NATURE { get; set; }
        public string JOB_TYPE { get; set; }
        public short CGPA_REQ { get; set; }
        public string JOB_LOCATION { get; set; }
        public Nullable<int> SALARY { get; set; }
        public short E_ID { get; set; }
    
        public virtual E_USERS E_USERS { get; set; }
    }
}
