//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ADMS
{
    using System;
    using System.Collections.Generic;
    
    public partial class JOB_SEEKERS
    {
        public short JS_ID { get; set; }
        public string JS_NAME { get; set; }
        public string JS_ADDRESS { get; set; }
        public long JS_PHONE { get; set; }
        public string JS_EMAIL { get; set; }
        public Nullable<System.DateTime> JS_DOB { get; set; }
        public string JS_EDUCATION { get; set; }
        public string JS_SKILLS { get; set; }
        public string JS_IMAGE { get; set; }
    
        public virtual JS_USERS JS_USERS { get; set; }
    }
}
