//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ADMS
{
    using System;
    using System.Collections.Generic;
    
    public partial class JS_USERS
    {
        public JS_USERS()
        {
            this.JOB_SEEKERS = new HashSet<JOB_SEEKERS>();
        }
    
        public short JS_ID { get; set; }
        public string JS_PASSWORD { get; set; }
    
        public virtual ICollection<JOB_SEEKERS> JOB_SEEKERS { get; set; }
    }
}
