//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ADMS
{
    using System;
    using System.Collections.Generic;
    
    public partial class PM_USERS
    {
        public PM_USERS()
        {
            this.PORTAL_MODERATORS = new HashSet<PORTAL_MODERATORS>();
            this.VERIFY_HISTORY = new HashSet<VERIFY_HISTORY>();
        }
    
        public short PM_ID { get; set; }
        public string PM_PASSWORD { get; set; }
    
        public virtual ICollection<PORTAL_MODERATORS> PORTAL_MODERATORS { get; set; }
        public virtual ICollection<VERIFY_HISTORY> VERIFY_HISTORY { get; set; }
    }
}
