//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ADMS
{
    using System;
    using System.Collections.Generic;
    
    public partial class PORTAL_MODERATORS
    {
        public short PM_ID { get; set; }
        public string PM_NAME { get; set; }
        public string PM_ADDRESS { get; set; }
        public long PM_PHONE { get; set; }
        public string PM_EMAIL { get; set; }
        public Nullable<System.DateTime> PM_JOIN_DATE { get; set; }
    
        public virtual PM_USERS PM_USERS { get; set; }
    }
}
